#+TITLE:        QPF Tech Talk
#+AUTHOR:       Jose C. Gonzalez
#+EMAIL:        JCGonzalez@sciops.esa.int
#+DATE:         Time-stamp: <2016-07-26 14:20:41 jcgonzalez>

#+SETUPFILE: ./config.org

* Overview of the Euclid QLA Processing Framework

** Abstract

*** 20160726-15:00
The Euclid SOC at ESAC, the only interface to the MOC, is responsible for receiving the housekeeping, pointing, and science data from MOC, derive Level 1 products for ingestion into the archive, as well as performing quick-look analysis and first level quality control of the data. For this purpose, the Quick Look Analysis subsystem must be able on the one hand to automatically check S/C data, produce and ingest reports in the Euclid Archive System within 48 hours from data retrieval to confirm that the data are correct and eventually quickly react to issues.  On the other hand, the QLA must facilitate data inspection by the user (mainly instrument scientists) in case further data analysis on the results is needed (e.g. being capable of accessing detectors data, showing it and/or exporting it to external programs).

In order to accomplish all these tasks, the QLA is composed of two major components, the QLA Diagnostic Tools (QDT), devoted to the execution of the actual checks on VIS (Visible Instrument) and NISP (Near-Infrared Spectro-Photometer) data; and the QLA Processing Framework (QPF), which provide the infrastructure needed for the QLA data processing and archiving.  The QPF capabilities, as main development drivers, include message-based communications, service oriented architecture, encapsulated task execution, database oriented internal data storage, system persistence, as well as a set of HMI application and tools to facilitate access to quality reports and processed data.

*** 20160726-16:303699 (GB)
The Euclid SOC at ESAC, the only interface from the SGS to the MOC, is responsible for receiving the housekeeping, pointing, and science data from MOC, derive Level 1 products for ingestion into the archive, as well as performing quick-look analysis and first level quality control of the data. For this purpose, the Quick Look Analysis subsystem must be able on the one hand to automatically check all S/C and instrument data, produce and ingest reports in the Euclid Archive System within 48 hours from data retrieval to confirm that the data are correct and eventually quickly trigger reaction to issues.  On the other hand, the QLA must facilitate data inspection by the user (mainly instrument scientists) in case further data analysis on the results is needed (e.g. being capable of accessing detectors data, showing it and/or exporting it to external programs).

In order to accomplish all these tasks, the QLA is composed of two major components, the QLA Diagnostic Tools (QDT), devoted to the execution of the actual checks on VIS (Visible Instrument) and NISP (Near-Infrared Spectro-Photometer) and HKTM data; and the QLA Processing Framework (QPF), which provide the infrastructure needed for the QLA data processing and archiving.  The QPF capabilities, as main development drivers, include message-based communications, service oriented architecture, encapsulated task execution, database oriented internal data storage, system persistence, as well as a set of HMI application and tools to facilitate access to quality reports and processed data.

** Outline
